import Head from "next/head";
import Image from "next/image";
import styles from "../styles/home.module.css";
import Navbar from "../components/Navbar";
import Header from "../components/Header";
import Seccion1 from "../components/Seccion1";
import Seccion2 from "../components/Seccion2"; 
import Seccion3 from "../components/Seccion3";
import Seccion4  from "../components/Seccion4";
import Seccion5 from "../components/Seccion5";
import Seccion6 from "../components/Seccion6";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"></link>
      </Head>
 
   <Navbar/>
   <Header/>
   <hr></hr>
   <Seccion1/>
   <Seccion2/>
   <Seccion3/>
   <Seccion4/>
   <hr></hr>
   <Seccion5/>
   <hr></hr>
   <Seccion6/>
   <hr></hr>
   <Footer/>
   





    
 
  
       
   
    
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
     
    </div>
  );
}
