import { Destination } from "../components/Admin/Destination";
import { Type } from "../components/Admin/Type";
import { Category } from "../components/Admin/Category";
import { Package } from "../components/Admin/Package/Package";
import { CustomPackage } from "../components/Admin/CustomPackage";
import styles from "../styles/Admin/Admin.module.scss";
import Head from "next/head";
import { getSession } from "next-auth/client"; //for user authentication (next-auth)

export default function Admin({ user }) {
  if (user === undefined || user.email !== "travellifetouroperator@gmail.com") {
    return (
      <>
        <p>You are not authorized to access this page.</p>
      </>
    );
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Admin panel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossOrigin="anonymous"
        ></link>
      </Head>
      <div></div>
      <h1>Admin Panel</h1>
      <div className={styles.grid}>
        <Destination />
        <Type />
        <Category />
      </div>
      <div className={styles.package}>
        <Package />
        <CustomPackage />
      </div>
      </div>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context);
  if (!session) {
    // context.res.writeHead(302, { Location: '/' });
    // context.res.end();
    return {
      props: {},
    };
  }
  return {
    props: {
      user: session.user,
    },
  };
}
