import Head from "next/head";
import {Galery} from "../components/DetailsTours/Galery";
import {Itinerary} from "../components/DetailsTours/Itinerary";
import {Nav} from "../components/DetailsTours/Nav";
import {Items} from "../components/DetailsTours/Items"
import {Map} from "../components/Map/Map"
import Image from "next/image";
import styles from "../styles/detailsTours/DetailTours.module.scss"

export default function DetailTours() {
  return (
    <div>
      <Head>
        <title>Turistic Life</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossOrigin="anonymous"
        ></link>
      </Head>
      <Image
        width={700}
        height={300}
        layout="responsive"
        src="/images/detailTour.jpg"
      />
      <Items/>
       <Nav/>
        <hr></hr>
         <Itinerary />
        <hr></hr>
        <Map/>
        <Galery />
        <hr></hr>
    </div>
  );
}
