import Head from "next/head";
import { Gallery } from "../components/DetailsTours/Gallery";
import { Itinerary } from "../components/DetailsTours/Itinerary";
import { NavBar } from "../components/DetailsTours/Nav";
import { Items } from "../components/DetailsTours/Items";
import Image from "../components/DetailsTours/Images";
import styles from "../styles/detailsTours/DetailTours.module.scss";
import { useParams } from "react-router"
import { useDispatch, useSelector } from "react-redux";
import { getAllDetails } from "../store/actions/DetailTours/detailActions";
import { useEffect } from "react"

export default function DetailTours() {
  // const { id } = useParams()
  const dispatch = useDispatch();
  const details = useSelector((state) => state.details);

    useEffect(() => {
    dispatch(getAllDetails())
  }, [dispatch]);

  return (
    <div>
      <Head>
        <title>Turistic Life</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossOrigin="anonymous"
        ></link>
      </Head>
      <div>
        {/* <div>{details?.packageName}</div> */}
        <section>
          
           <Image/> 
             <Items/>
      
        </section>
          
        
      </div>
      <NavBar />
  
    </div>
  );
}
