import Head from "next/head";
import { Cover } from "../components/Home/Cover";
import { MapContainer } from "../components/Home/MapContainer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Across the globe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossOrigin="anonymous"
        ></link>
      </Head>
      <Cover />
      <MapContainer />
    </div>
  );
}

// AIzaSyDUfwrf9MfP5REYjQYDY1ewufTbwp2JUNE
