import { TourCards } from "../components/Tours/TourCards";
import { FilterContainer } from "../components/Tours/FilterContainer";
import styles from "../styles/tours/ToursInformation.module.scss";
import { useState, useEffect } from "react";
import Image from "next/image";
import { useSelector, useDispatch } from "react-redux";
import { getAllPackages } from "../store/actions/Packages/packagesActions";
import Head from "next/head";
import { LoadingScreen } from "../components/LoadingScreen/LoadingScreen";

export default function Tours() {
  const dispatch = useDispatch();
  const [packagesStore] = useSelector((state) => state.packages);
  const [packages, setPackages] = useState();
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    dispatch(getAllPackages());
  }, []);

  useEffect(() => {
    setPackages(packagesStore);
  }, [packagesStore]);

  useEffect(() => {
    packages && setLoading(false);
  }, [packages]);

  return loading ? (
    <LoadingScreen />
  ) : (
    <div>
      <Head>
        <title>Our Tours</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossOrigin="anonymous"
        ></link>
      </Head>
      <div className={styles.imageContainer}>
        <div></div>

        <h2>Travels</h2>
      </div>
      <div className={styles.intro}>
        <blockquote>
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptas
          pariatur voluptates enim aliquam consequuntur necessitatibus dolorem
          repudiandae dolorum illo ex atque reprehenderit, beatae natus ducimus
          eaque consectetur? Quasi, itaque error? Praesentium consectetur
          placeat quas nisi ullam. Animi sed eaque recusandae laborum
          laudantium, deserunt magnam numquam accusantium incidunt architecto
          hic officia.
        </blockquote>
      </div>
      <div className={styles.container}>
        <div>
          <FilterContainer setPackages={setPackages} />
        </div>
        <div className={styles.card}>
          <TourCards packages={packages} />
        </div>
      </div>
    </div>
  );
}
